version: 2
general:
  branches:
    only:
      - master # ignore development branches, only build master
jobs:
  build:
    docker:
      - image: ocaml/opam2
    steps:
      - checkout
      - run:
          name: Install OCaml packages
          command: sudo apt-get install -y m4 && opam install -y ounit menhir dune
      - run:
          name: Install Python 2.7
          command: sudo apt-get update && sudo apt-get install --yes python2.7
      - run:
          name: Build Linguine 
          command: eval $(opam env) && make build 
      - run:
          name: Run Linguine examples
          command: eval $(opam env) && make build && python2.7 test.py -b
